don't send data in case of error
in case of error, just send [failed] = 1 otherwise send all collected data

diff --git a/zbxApacheStatusCheck b/zbxApacheStatusCheck
--- a/zbxApacheStatusCheck
+++ b/zbxApacheStatusCheck
@@ -247,53 +247,53 @@ fi
 eval $GET_CMD > $STATUSFILE
 RET_VAL=$?
 
-# tall zabbix about some failure getting data
-echo -n "\"$ZABBIXSOURCE\" \"custom.apache[failed]\" " >> $SENDERFILE
+# in case of error, just send [failed] = 1
+# otherwise send all collected data
 if [[ $RET_VAL = 0 ]]; then
-	echo 0 >> $SENDERFILE
-else
-	echo 1 >> $SENDERFILE;
-fi
+	echo "\"$ZABBIXSOURCE\" \"custom.apache[failed]\" 0" >> $SENDERFILE
 
-# read the config file to get all relevant statistics
-while read STATNAME
-do
-	if [[ $STATNAME = "Scoreboard" ]]; then
-		SCOREBOARD=`fgrep -w "$STATNAME:" $STATUSFILE | sed "s/$STATNAME: //"`
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[WaitingForConnection]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,"_")}' >> $SENDERFILE
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[StartingUp]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,"S")}' >> $SENDERFILE
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[ReadingRequest]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,"R")}' >> $SENDERFILE
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[SendingReply]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,"W")}' >> $SENDERFILE
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[KeepAlive]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,"K")}' >> $SENDERFILE
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[DNSLookup]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,"D")}' >> $SENDERFILE
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[ClosingConnection]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,"C")}' >> $SENDERFILE
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[Logging]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,"L")}' >> $SENDERFILE
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[GracefullyFinishing]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,"G")}' >> $SENDERFILE
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[IdleCleanupOfWorker]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,"I")}' >> $SENDERFILE
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[OpenSlotWithNoCurrentProcess]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,".")}' >> $SENDERFILE
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[TotalWorkers]\" " >> $SENDERFILE
-		echo $SCOREBOARD | awk '{print split($1,dummy,"")}' >> $SENDERFILE
-	else
-		echo -n "\"$ZABBIXSOURCE\" \"custom.apache[$STATNAME]\" " >> $SENDERFILE
-		LINE=`fgrep -w "$STATNAME:" $STATUSFILE`
-		if [[ $? = 0 ]]; then
-			echo $LINE | sed "s/$STATNAME: //" >> $SENDERFILE
+	# read the config file to get all relevant statistics
+	while read STATNAME
+	do
+		if [[ $STATNAME = "Scoreboard" ]]; then
+			SCOREBOARD=`fgrep -w "$STATNAME:" $STATUSFILE | sed "s/$STATNAME: //"`
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[WaitingForConnection]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,"_")}' >> $SENDERFILE
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[StartingUp]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,"S")}' >> $SENDERFILE
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[ReadingRequest]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,"R")}' >> $SENDERFILE
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[SendingReply]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,"W")}' >> $SENDERFILE
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[KeepAlive]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,"K")}' >> $SENDERFILE
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[DNSLookup]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,"D")}' >> $SENDERFILE
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[ClosingConnection]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,"C")}' >> $SENDERFILE
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[Logging]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,"L")}' >> $SENDERFILE
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[GracefullyFinishing]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,"G")}' >> $SENDERFILE
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[IdleCleanupOfWorker]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,"I")}' >> $SENDERFILE
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[OpenSlotWithNoCurrentProcess]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,".")}' >> $SENDERFILE
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[TotalWorkers]\" " >> $SENDERFILE
+			echo $SCOREBOARD | awk '{print split($1,dummy,"")}' >> $SENDERFILE
 		else
-			echo 0 >> $SENDERFILE;
+			echo -n "\"$ZABBIXSOURCE\" \"custom.apache[$STATNAME]\" " >> $SENDERFILE
+			LINE=`fgrep -w "$STATNAME:" $STATUSFILE`
+			if [[ $? = 0 ]]; then
+				echo $LINE | sed "s/$STATNAME: //" >> $SENDERFILE
+			else
+				echo 0 >> $SENDERFILE;
+			fi
 		fi
-	fi
-done < $CONFIGFILE
+	done < $CONFIGFILE
+else
+	echo "\"$ZABBIXSOURCE\" \"custom.apache[failed]\" 1" >> $SENDERFILE
+fi
 
 # Send all information to Zabbix using zbbix_sender
 SENDER_CMD="$SENDER -v --zabbix-server $ZABBIXSERVER --port $ZABBIXPORT --input-file $SENDERFILE"
